# Example config file.

#Output            = "test.h5"
SwarmSize         = 75
Steps             = 10000
Dt                = 0.1
Speed             = 1.0
BodyWidth         = 0.125
BodyOffset        = 0.8
MaxTurn           = 1.5
SigmaNoise        = 0.25
AttenuationLength = 3.0
MaxAngle          = 0.01
MaxContrast       = 0.1
DomainType        = "finite"
DomainSize        = 50.0
