# Example config file.

#Output            = "test.h5"
SwarmSize         = 75
Steps             = 10000
Dt                = 0.1
BodyWidth         = 0.125
BodyOffset        = 0.8
Mass              = 1.0
Alpha             = 1.2
Beta              = 0.5
Cr                = 2.0
Lr                = 1.0
Ca                = 0.0
La                = 4.0
AttenuationLength = 6.0
ContrastType      = "michelson"
MaxAngle          = 0.01
MaxContrast       = 0.1
DomainType        = "finite"
DomainSize        = 50.0
