# Example config file.

#Output            = "test.h5"
SwarmSize         = 75
Steps             = 10000
Dt                = 0.1
BodyWidth         = 0.125
BodyOffset        = 0.8
Mass              = 1
Alpha             = 1.2
Beta              = 0.37
Cr                = 2
Lr                = 1
Ca                = 1
La                = 4
AttenuationLength = 3.0
ContrastType      = "michelson"
MaxAngle          = 0.01
MaxContrast       = 0.1
DomainType        = "finite"
DomainSize        = 50.0
