# Example config file.

#Output            = "test.h5"

SwarmSize         = 100
Steps             = 10000
Dt                = 0.1

BodyWidth         = 0.125
BodyOffset        = 0.8

Model             = "D'Orsogna 2005"
Mode              = "active"

Speed             = 2.0
Zor               = 1.0
Zoo               = 2.5
Zoa               = 16.5
BlindAngle        = 90.0
MaxTurn           = 90.0
SDError           = 1.0

Mass              = 1.0
Alpha             = 2.0
Beta              = 0.5
Cr                = 6.0
Lr                = 1.0
Ca                = 4.0
La                = 4.0
Co                = 0.5
Lo                = 2.0
Cs                = 4.0
Ls                = 4.0

AttenuationLength = 6.0
ContrastType      = "michelson"
MaxAngle          = 0.01
MaxContrast       = 0.1

DomainType        = "periodic"
DomainSize        = 100.0
