# Example config file.

Output            = "/Users/sleblanc/data/static-analysis/fulldetectid.h5"
SwarmSize         = 300
Replicates        = 6333
BodyWidth         = 0.125
BodyOffset        = 0.8
AttenuationLength = 1000.0
ContrastType      = "michelson"
MaxAngle          = 0.001
MaxContrast       = 0.1
SchoolMajorRadius = 15.0
SchoolMinorRadius = 10.0
SchoolScale       = 1.0
SchoolType        = "data"
SchoolDataPath    = "/Users/sleblanc/data/static-analysis/fulldata.h5"
GridXmin          = -50.0
GridXmax          = 50.0
GridXcount        = 100
GridYmin          = -50.0
GridYmax          = 50.0
GridYcount        = 100
