# Example config file.

Output            = "/Users/sleblanc/data/static-analysis/fullprocessed.h5"
SwarmSize         = 300
Replicates        = 6333
BodyWidth         = 0.125
BodyOffset        = 0.8
AttenuationLength = 1000.0
ContrastType      = "michelson"
MaxAngle          = 0.02
MaxContrast       = 0.1
SchoolMajorRadius = 15.0
SchoolMinorRadius = 10.0
SchoolScale       = 1.0
SchoolType        = "data"
SchoolDataPath    = "/Users/sleblanc/data/static-analysis/fulldata.h5"
