# Example config file.

Output            = "/Users/igoumiri/go/src/github.com/PrincetonUniversity/static-analysis/test.h5"
#Output            = "test.h5"
SwarmSize         = 300
Replicates        = 12004
BodyWidth         = 0.125
BodyOffset        = 0.8
AttenuationLength = 1000.0
ContrastType      = "michelson"
MaxAngle          = 0.01
MaxContrast       = 0.1
SchoolMajorRadius = 15.0
SchoolMinorRadius = 10.0
SchoolType        = "data"
SchoolDataPath    = "/Users/igoumiri/go/src/github.com/PrincetonUniversity/static-analysis/colin.h5"
