# Example config file.

#Output            = "test.h5"
SwarmSize         = 300
Replicates        = 100
BodyWidth         = 0.125
BodyOffset        = 0.8
AttenuationLength = 1000.0
ContrastType      = "michelson"
MaxAngle          = 0.01
MaxContrast       = 0.1
DomainSize        = 30.0
